### ISSUE TITLE
ADDing IR Sensor

### ISSUE THREAD

**Issue by annak1n** [croningp/commanduino#14]
I have a question.. can i connect sensor like **Sharp IR Sensor GP2Y0A21YK0F** or HC-SR04 or GPS NEO ?

**Comment by Tyrannican** [comment]
In order to add a new device, you will need to add a device in the [Arduino CommandTools](https://github.com/croningp/Arduino-CommandTools) library for the given device then add a supporting Python implementation in the Commanduino side.

Just follow the layout of other devices in the Arduino Command Tools library for a guide!
